// <auto-generated />
namespace MeetingOrganizer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class columnAdded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(columnAdded));
        
        string IMigrationMetadata.Id
        {
            get { return "202112011016042_columnAdded"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
